-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.blockchain_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  transaction_hash character varying NOT NULL,
  block_number bigint,
  booking_id character varying,
  event_data jsonb NOT NULL,
  processed_at timestamp with time zone DEFAULT now(),
  processing_status character varying DEFAULT 'PROCESSED'::character varying CHECK (processing_status::text = ANY (ARRAY['PROCESSED'::character varying, 'FAILED'::character varying, 'RETRY'::character varying]::text[])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blockchain_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.booking_session_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  provider_total_duration integer,
  customer_total_duration integer,
  provider_sessions jsonb,
  customer_sessions jsonb,
  last_checked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_session_data_pkey PRIMARY KEY (id),
  CONSTRAINT booking_session_data_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  service_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text, 'pending_payment'::text, 'paid'::text, 'pending_completion'::text, 'pending_cancellation'::text, 'failed'::text])),
  scheduled_at timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL,
  total_price numeric NOT NULL,
  service_fee numeric NOT NULL DEFAULT 0.00,
  customer_notes text,
  provider_notes text,
  location text,
  is_online boolean DEFAULT false,
  meeting_link text,
  cancellation_reason text,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  meeting_platform character varying,
  meeting_id text,
  meeting_settings jsonb DEFAULT '{}'::jsonb,
  cancellation_policy_id uuid,
  cancellation_explanation text,
  refund_amount numeric CHECK (refund_amount >= 0::numeric),
  provider_earnings numeric CHECK (provider_earnings >= 0::numeric),
  platform_fee numeric CHECK (platform_fee >= 0::numeric),
  reminder_24h_sent timestamp with time zone,
  reminder_1h_sent timestamp with time zone,
  reminder_15m_sent timestamp with time zone,
  auto_status_updated boolean DEFAULT false,
  blockchain_booking_id character varying CHECK (blockchain_booking_id IS NULL OR blockchain_booking_id::text ~ '^0x[a-fA-F0-9]{64}$'::text),
  blockchain_tx_hash character varying CHECK (blockchain_tx_hash IS NULL OR blockchain_tx_hash::text ~ '^0x[a-fA-F0-9]{64}$'::text),
  blockchain_confirmed_at timestamp with time zone,
  completion_tx_hash character varying CHECK (completion_tx_hash IS NULL OR completion_tx_hash::text ~ '^0x[a-fA-F0-9]{64}$'::text),
  cancellation_tx_hash character varying CHECK (cancellation_tx_hash IS NULL OR cancellation_tx_hash::text ~ '^0x[a-fA-F0-9]{64}$'::text),
  blockchain_data jsonb,
  auto_complete_blocked boolean DEFAULT false,
  auto_complete_blocked_reason text,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id),
  CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.users(id),
  CONSTRAINT bookings_cancellation_policy_id_fkey FOREIGN KEY (cancellation_policy_id) REFERENCES public.cancellation_policies(id)
);
CREATE TABLE public.cancellation_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reason_key text NOT NULL UNIQUE,
  reason_title text NOT NULL,
  reason_description text NOT NULL,
  customer_refund_percentage integer NOT NULL CHECK (customer_refund_percentage >= 0 AND customer_refund_percentage <= 100),
  provider_earnings_percentage integer NOT NULL CHECK (provider_earnings_percentage >= 0 AND provider_earnings_percentage <= 100),
  platform_fee_percentage integer NOT NULL CHECK (platform_fee_percentage >= 0 AND platform_fee_percentage <= 100),
  requires_explanation boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cancellation_policies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cancellation_policy_conditions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  condition_type text NOT NULL CHECK (condition_type = ANY (ARRAY['booking_status'::text, 'time_before_start'::text, 'min_time_before_start'::text, 'max_time_before_start'::text])),
  condition_value text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cancellation_policy_conditions_pkey PRIMARY KEY (id),
  CONSTRAINT cancellation_policy_conditions_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.cancellation_policies(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  color text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user1_id uuid,
  user2_id uuid,
  last_message_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_user1_id_fkey FOREIGN KEY (user1_id) REFERENCES public.users(id),
  CONSTRAINT conversations_user2_id_fkey FOREIGN KEY (user2_id) REFERENCES public.users(id)
);
CREATE TABLE public.file_uploads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type text,
  upload_type text CHECK (upload_type = ANY (ARRAY['avatar'::text, 'service_image'::text, 'message_attachment'::text, 'document'::text])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT file_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT file_uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  sender_id uuid,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['booking_request'::text, 'booking_confirmed'::text, 'booking_cancelled'::text, 'payment_received'::text, 'new_review'::text, 'message'::text, 'reminder'::text])),
  title text NOT NULL,
  content text NOT NULL,
  data jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  amount numeric NOT NULL,
  service_fee numeric NOT NULL DEFAULT 0.00,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'held'::text, 'released'::text, 'refunded'::text, 'failed'::text])),
  payment_method_id text,
  payment_intent_id text,
  held_at timestamp without time zone,
  released_at timestamp without time zone,
  refunded_at timestamp without time zone,
  refund_reason text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT payments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id)
);
CREATE TABLE public.provider_availability (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  provider_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  timezone text DEFAULT 'UTC'::text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT provider_availability_pkey PRIMARY KEY (id),
  CONSTRAINT provider_availability_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL UNIQUE,
  reviewer_id uuid NOT NULL,
  reviewee_id uuid NOT NULL,
  service_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  is_public boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES public.users(id),
  CONSTRAINT reviews_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  provider_id uuid NOT NULL,
  category_id uuid,
  title text NOT NULL,
  description text NOT NULL,
  short_description text,
  price numeric NOT NULL,
  duration_minutes integer NOT NULL,
  location text,
  is_online boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  review_count integer DEFAULT 0,
  total_bookings integer DEFAULT 0,
  images ARRAY,
  tags ARRAY,
  availability_schedule jsonb,
  requirements text,
  cancellation_policy text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  meeting_platform character varying CHECK (meeting_platform::text = ANY (ARRAY['google_meet'::character varying, 'zoom'::character varying, 'teams'::character varying]::text[])),
  meeting_settings jsonb DEFAULT '{}'::jsonb,
  service_timezone text DEFAULT 'UTC'::text,
  is_visible boolean DEFAULT true,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id),
  CONSTRAINT services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.signature_nonces (
  id integer NOT NULL DEFAULT nextval('signature_nonces_id_seq'::regclass),
  nonce bigint NOT NULL UNIQUE,
  used_at timestamp with time zone DEFAULT now(),
  booking_id uuid,
  signature_type character varying NOT NULL,
  CONSTRAINT signature_nonces_pkey PRIMARY KEY (id),
  CONSTRAINT signature_nonces_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['booking_payment'::character varying, 'inviter_fee'::character varying, 'bonus'::character varying, 'refund'::character varying]::text[])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  booking_id uuid,
  source_user_id uuid,
  service_id uuid,
  description text NOT NULL CHECK (TRIM(BOTH FROM description) <> ''::text),
  transaction_hash character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id),
  CONSTRAINT transactions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT transactions_source_user_id_fkey FOREIGN KEY (source_user_id) REFERENCES public.users(id),
  CONSTRAINT transactions_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.user_favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  service_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT user_favorites_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT user_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_meeting_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform character varying NOT NULL CHECK (platform::text = ANY (ARRAY['google_meet'::character varying, 'zoom'::character varying, 'teams'::character varying]::text[])),
  access_token text NOT NULL,
  refresh_token text,
  expires_at timestamp with time zone,
  scope ARRAY,
  platform_user_id text,
  platform_user_email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_meeting_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT user_meeting_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  display_name text,
  bio text,
  location text,
  avatar text,
  phone text,
  is_verified boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  review_count integer DEFAULT 0,
  total_earnings numeric DEFAULT 0.00,
  total_spent numeric DEFAULT 0.00,
  is_provider boolean DEFAULT false,
  provider_verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  timezone text DEFAULT 'UTC'::text,
  username text CHECK (username ~ '^[a-zA-Z0-9_-]{3,30}$'::text),
  wallet_address character varying UNIQUE CHECK (wallet_address::text ~ '^0x[a-fA-F0-9]{40}$'::text),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);