[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
optimizer = true
optimizer_runs = 200
via_ir = false

# Base Sepolia (testnet) - for development
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"

# Etherscan V2 API Configuration
[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }

# Gas optimization
[profile.default.optimizer_details]
yul = true

# Enhanced testing
[profile.test]
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
